# -----------------
# Global variables
# -----------------
# Name of the project
name: OpenAB

# Subtitle - shown in the header of the website
subtitle: Open Agent Benchmark Initiative for Parallel and Distributed Benchmarking

# Meta description (<=160 characters) - used by search engines
description: The Open Agent Benchmark is ... (@todo)


# -----------------
# Jekyll settings
# -----------------

# Exclude files or directories from being hosted on the web
exclude: ['package.json', 'readme.md']

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Timezone for date/time used on the website
timezone: Europe/London

# Local development configuration settings
source: .
destination: ./_site
host: 0.0.0.0
port: 4000
baseurl: 
url: http://localhost:4000
lsi: false

# Markdown processing settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
